;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mark-sexp
        paredit-backward-slurp-sexp
        paredit-backward-up
        paredit-close-round
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-up
        paredit-open-round
        slime-space
        ))

(setq mc/cmds-to-run-once
      '(
        ))
