;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-dwim
        TeX-insert-backslash
        TeX-insert-sub-or-superscript
        ace-jump-mode
        backward-sentence
        backward-sexp
        beginning-of-visual-line
        c-electric-semi&comma
        delete-horizontal-space
        delete-indentation
        dired-next-line
        downcase-region
        end-of-visual-line
        forward-sexp
        indent-new-comment-line
        isearch-abort
        isearch-backward-regexp
        isearch-exit
        isearch-forward-regexp
        isearch-printing-char
        iy-go-to-char--command
        kill-region
        kill-sexp
        kill-visual-line
        mark-sexp
        mouse-yank-primary
        multiply-last-sexp-2
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-metaright
        org-return
        org-self-insert-command
        org-todo
        paredit-backward
        paredit-backward-kill-word
        paredit-backward-slurp-sexp
        paredit-backward-up
        paredit-close-round
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-kill
        paredit-open-round
        paredit-splice-sexp
        paredit-splice-sexp-killing-backward
        reindent-then-newline-and-indent
        slime-export-symbol-at-point
        slime-space
        smex
        transpose-sexps
        transpose-words
        wdired-downcase-word
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        copy-line-to-other-window
        isearch-delete-char
        isearch-other-control-char
        slime-compile-defun
        slime-selector-or-start
        ))
